Repository STANL-2/STANL_Backend, pull requests merged in 2024-10, with the labels that each got.

#149 [Product] 공유물품 테스트 코드
  src/main/java/stanl_2/weshareyou/domain/product/service/ProductServiceImpl.java
  src/test/java/stanl_2/weshareyou/domain/product/service/ProductServiceImplTests.java
Labels: test

#151 [Notice] 비활성화 상태 필터링
  src/main/java/stanl_2/weshareyou/domain/notice/service/NoticeServiceImpl.java
Labels: refactor

#153 [Board] 게시글 생성 & 조회 refactoring
  src/main/java/stanl_2/weshareyou/domain/board/aggregate/entity/Board.java
  src/main/java/stanl_2/weshareyou/domain/board/controller/BoardController.java
  src/main/java/stanl_2/weshareyou/domain/board/service/BoardServiceImpl.java
  src/main/java/stanl_2/weshareyou/domain/board_image/aggregate/entity/BoardImage.java
  src/main/java/stanl_2/weshareyou/domain/board_image/service/BoardImageService.java
  src/main/java/stanl_2/weshareyou/domain/board_image/service/BoardImageServiceImpl.java
  src/main/java/stanl_2/weshareyou/domain/chat/controller/ChatRoomController.java
  src/main/java/stanl_2/weshareyou/global/common/exception/ErrorCode.java
Labels: refactor

#155 [Member] 모든 api 점검
  src/main/java/stanl_2/weshareyou/domain/member/aggregate/vo/request/FindIdRequestVO.java
  src/main/java/stanl_2/weshareyou/domain/member/controller/MemberController.java
  src/main/java/stanl_2/weshareyou/domain/member/repository/MemberRepository.java
  src/main/java/stanl_2/weshareyou/domain/member/service/MemberServiceImpl.java
  src/main/java/stanl_2/weshareyou/global/api/redis/RedisService.java
  src/main/java/stanl_2/weshareyou/global/api/redis/RedisServiceImpl.java
  src/main/java/stanl_2/weshareyou/global/api/sms/SmsService.java
  src/main/java/stanl_2/weshareyou/global/api/sms/SmsServiceImpl.java
  src/main/java/stanl_2/weshareyou/global/api/smtp/MailService.java
  src/main/java/stanl_2/weshareyou/global/api/smtp/MailServiceImpl.java
  src/main/java/stanl_2/weshareyou/global/config/SmsConfig.java
  src/main/java/stanl_2/weshareyou/global/security/filter/JWTTokenValidatorFilter.java
  src/main/java/stanl_2/weshareyou/global/security/filter/TokenFilter.java
Labels: bug, refactor
